### ISSUE TITLE
Question about Breadcrumbs extension

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson-Breadcrumbs-Extension#2]
Hello

I use Breadcrumbs extension and Translation extension, is it possible to split Breadcrumbs settings for all used languages?

![sc](https://cloud.githubusercontent.com/assets/12991525/8638036/507fdca2-28b5-11e5-8bdf-b9dabdd227f0.png)

Thanks :)

**Comment by llemurya** [comment]
@WPJobs at the moment it is not possible to do this thing. We must analyze when to do this work, maybe in the next roadmap of the translation that will include the string translation it will be done , because the breadcrumbs settings is set as strings in database.
